In [1]:
import pandas as pd

campaigns = pd.read_csv("campaigns.csv")
channel_spend = pd.read_csv("channel_spend.csv")
leads = pd.read_csv("leads_conversions.csv")
customers = pd.read_csv("customers.csv")

In [3]:
campaigns.head()

,campaign_id,campaign_name,product_category,brand,start_date,end_date,total_budget,region,season_tag
0,1,Nescafé Campaign 1,Beverages,Nescafé,2024-10-08,2024-11-12,7989709,South,Diwali
1,2,Milo Campaign 2,Beverages,Milo,2024-02-02,2024-02-23,3643890,South,Summer
2,3,Nescafé Campaign 3,Beverages,Nescafé,2025-10-27,2025-12-20,14576749,South,Regular
3,4,Cerelac Campaign 4,Dairy-Nutrition,Cerelac,2024-06-12,2024-07-29,11916912,East,Summer
4,5,Munch Campaign 5,Confectionery,Munch,2024-04-14,2024-05-09,13248244,North,Back-to-School

In [5]:
campaigns.head()

,campaign_id,campaign_name,product_category,brand,start_date,end_date,total_budget,region,season_tag
0,1,Nescafé Campaign 1,Beverages,Nescafé,2024-10-08,2024-11-12,7989709,South,Diwali
1,2,Milo Campaign 2,Beverages,Milo,2024-02-02,2024-02-23,3643890,South,Summer
2,3,Nescafé Campaign 3,Beverages,Nescafé,2025-10-27,2025-12-20,14576749,South,Regular
3,4,Cerelac Campaign 4,Dairy-Nutrition,Cerelac,2024-06-12,2024-07-29,11916912,East,Summer
4,5,Munch Campaign 5,Confectionery,Munch,2024-04-14,2024-05-09,13248244,North,Back-to-School

In [6]:
campaigns.shape

channel_spend.shape

leads.shape

customers.shape

(5000, 6)

In [7]:
campaigns.shape

(100, 9)

In [8]:
campaigns.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       100 non-null    int64
 1   campaign_name     100 non-null    str
 2   product_category  100 non-null    str
 3   brand             100 non-null    str
 4   start_date        100 non-null    str
 5   end_date          100 non-null    str
 6   total_budget      100 non-null    int64
 7   region            100 non-null    str
 8   season_tag        100 non-null    str
dtypes: int64(2), str(7)
memory usage: 4.4 KB

In [9]:
campaigns.describe(include="all")

,campaign_id,campaign_name,product_category,brand,start_date,end_date,total_budget,region,season_tag
count,100.000000,100,100,100,100,100,1.000000e+02,100,100
unique,NaN,100,4,7,94,96,NaN,6,4
top,NaN,Nescafé Campaign 1,Beverages,Maggi,2024-04-24,2024-05-18,NaN,Metro,Back-to-School
freq,NaN,1,30,25,2,2,NaN,21,28
mean,50.500000,NaN,NaN,NaN,NaN,NaN,1.046256e+07,NaN,NaN
std,29.011492,NaN,NaN,NaN,NaN,NaN,5.433687e+06,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,6.860530e+05,NaN,NaN
25%,25.750000,NaN,NaN,NaN,NaN,NaN,6.287058e+06,NaN,NaN
50%,50.500000,NaN,NaN,NaN,NaN,NaN,1.007502e+07,NaN,NaN
75%,75.250000,NaN,NaN,NaN,NaN,NaN,1.500381e+07,NaN,NaN
max,100.000000,NaN,NaN,NaN,NaN,NaN,1.998136e+07,NaN,NaN

In [10]:
channel_spend.isnull().sum()

spend_id          0
campaign_id       0
channel           0
platform        163
spend_amount      0
impressions       0
clicks          163
grps            423
dtype: int64

In [11]:
channel_spend.shape

(500, 8)

In [12]:
channel_spend[channel_spend["clicks"].isnull()]["channel"].value_counts()

channel
OOH    86
TV     77
Name: count, dtype: int64

In [13]:
channel_spend[channel_spend["grps"].isnull()]["channel"].value_counts()

channel
Digital-Search    92
OOH               86
Trade-Promo       86
In-store          84
Digital-Social    75
Name: count, dtype: int64

In [14]:
channel_spend[channel_spend["platform"].isnull()]["channel"].value_counts()

channel
OOH    86
TV     77
Name: count, dtype: int64

In [15]:
campaigns.duplicated().sum()

np.int64(0)

In [16]:
channel_spend.duplicated().sum()

np.int64(0)

In [17]:
leads.duplicated().sum()

np.int64(0)

In [18]:
customers.duplicated().sum()

np.int64(0)

In [19]:
campaigns["campaign_id"].duplicated().sum()

np.int64(0)

In [20]:
channel_spend["spend_id"].duplicated().sum()

np.int64(0)

In [21]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [23]:
leads["record_id"].duplicated().sum()

np.int64(0)

### Primary Key Validation
Primary keys were checked for duplicate values using the `duplicated()` method. All primary key columns (`campaign_id`, `spend_id`, `customer_id`, `record_id`) contained unique values with zero duplicates. This confirms the integrity of each table and ensures reliable joins and analysis.

Foreign Key Validation

In [24]:
set(channel_spend["campaign_id"]) - set(campaigns["campaign_id"])

set()

In [25]:
set(leads["campaign_id"]) - set(campaigns["campaign_id"])

set()

Logical Data Validation

In [27]:
#Campaign duration should never be negative
(campaigns["end_date"] < campaigns["start_date"]).sum()

np.int64(0)

In [28]:
#Channel Spend should never be negative
(channel_spend["spend_amount"] < 0).sum()

np.int64(0)

In [29]:
#Clicks cannot exceed impressions
(channel_spend["clicks"] > channel_spend["impressions"]).sum()

np.int64(0)

In [30]:
#Impressions should never be negative
(channel_spend["impressions"] < 0).sum()

np.int64(0)

Leads & Conversions

In [31]:
#Revenue cannot be negative
(leads["revenue_generated"] < 0).sum()

np.int64(0)

In [32]:
#Conversions cannot exceed leads
(leads["conversions"] > leads["leads_generated"]).sum()

np.int64(0)

In [33]:
#Leads generated should never be negative
(leads["leads_generated"] < 0).sum()

np.int64(0)

Customers

In [34]:
#Customer acquisition cost cannot be negative
customers.describe()

,customer_id,acquisition_campaign_id,first_purchase_value,repeat_purchase_count,total_ltv
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,50.130800,803.137800,6.013400,3978.205600
std,1443.520003,28.959921,403.230588,3.766067,2565.699975
min,1.000000,1.000000,100.000000,0.000000,104.000000
25%,1250.750000,24.000000,454.000000,3.000000,1932.750000
50%,2500.500000,50.000000,804.500000,6.000000,3428.000000
75%,3750.250000,75.000000,1154.000000,9.000000,5533.500000
max,5000.000000,100.000000,1500.000000,12.000000,12149.000000

Convert Date Columns

In [35]:
#Check the data types first:
campaigns.info()
leads.info()
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       100 non-null    int64
 1   campaign_name     100 non-null    str
 2   product_category  100 non-null    str
 3   brand             100 non-null    str
 4   start_date        100 non-null    str
 5   end_date          100 non-null    str
 6   total_budget      100 non-null    int64
 7   region            100 non-null    str
 8   season_tag        100 non-null    str
dtypes: int64(2), str(7)
memory usage: 4.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_id          500 non-null    int64
 1   campaign_id        500 non-null    int64
 2   channel            500 non-null    str
 3   leads_generated    500 non-null    int64
 4   conversions        500 non-null    int64
 5   revenue_generated  500 non-null    float64
dtypes: float64(1), int64(4), str(1)
memory usage: 21.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              5000 non-null   int64
 1   acquisition_campaign_id  5000 non-null   int64
 2   acquisition_channel      5000 non-null   str
 3   first_purchase_value     5000 non-null   int64
 4   repeat_purchase_count    5000 non-null   int64
 5   total_ltv                5000 non-null   int64
dtypes: int64(5), str(1)
memory usage: 214.9 KB

start_date is stored as string
end_date is stored as string

#Dates should never remain as strings if you want to perform date calculations.

In [38]:
#Convert date columns as they are still object/string:

campaigns["start_date"] = pd.to_datetime(campaigns["start_date"])
campaigns["end_date"] = pd.to_datetime(campaigns["end_date"])

Feature Engineering

In [39]:
#Create a campaign duration column.

campaigns["campaign_duration"] = (campaigns["end_date"] - campaigns["start_date"]).dt.days

In [40]:
campaigns.to_csv("campaigns_cleaned.csv", index=False)

channel_spend.to_csv("channel_spend_cleaned.csv", index=False)

leads.to_csv("leads_conversions_cleaned.csv", index=False)

customers.to_csv("customers_cleaned.csv", index=False)